services:
  wppconnect:
    build:
      context: .
    volumes:
      - /media/pi/Backup/docker/config.ts:/usr/src/wpp-server/config.ts
      - /media/pi/Backup/docker/wppconnect_tokens:/usr/src/wpp-server/tokens
    ports:
      - "21465:21465"

volumes:
  wppconnect_tokens: {}